# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Github CI

on:
  push:
    branches:
     - main

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Nextjs
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ut2ADwNsSdqsik2NaI58ODyejwLt/NelCZRv7Pu
